### ISSUE TITLE
quantitization rules questions

### ISSUE THREAD

**Issue by jveejay** [mlperf/inference_policies#20] opened 2019-07-19 13:16 UTC
@guschmue asks, "Say I have a runtime that takes fp16 but internally uses 4 bit – can one submit this in closed?"

"We’d load the weights as fp16 but internally activations and weights would be 4 bit. We’d use calibration using the published list."

**Comment by jveejay** [comment] 2019-07-19 13:20
@DilipSequeira says, “if you think you’re skating close to the edge, get it whitelisted.” - so there aren’t surprises come submission day."

**Comment by jveejay** [comment] 2019-07-19 13:20
@jveejay "In this scheme, is it to be considered a 4-bit quantization scheme or a fp16 scheme?"

**Comment by jveejay** [comment] 2019-07-19 13:21
@guschmue  "Ah, that is why I started to ask.
What we’d load is fp16 so maybe it is fp16 and since 4 bit is only internal mlperf should not care.
But is not black and white so walking over it is good practice."

**Comment by jveejay** [comment] 2019-07-19 13:21
@DilipSequeira says,

"It’s hybrid.
 
Since you can’t start with a prequantized model here, you’ll need to describe your quantization scheme in a way that can be reproduced (I thought we had decided on a different standard, but I see it’s what’s in the rules right now) and so the bit width will be exposed.
 
And our general guidance has been “if you think you’re skating close to the edge, get it whitelisted.” - so there aren’t surprises come submission day."

**Comment by guschmue** [comment] 2019-07-24 15:12
For some models we need to calibrate. For gnmt (that one is the one we care about for 0.5)
we don't need to re-train or calibrate and take the weights unchanged as fp16.
Internally use 4 bit.  Does this count as fp16 ?

**Comment by tjablin** [comment] 2019-07-24 15:48
I think this counts as 4-bit weights.

**Comment by DilipSequeira** [comment] 2019-07-24 16:18
I don't think we have the right standard for exposing quantization - much though I would be interested to see how everyone else is doing it, what we should really care about is that it's a function of the input model and the calibration set, and generalizes across a wide range of models. 

That's less strict than publishing it to the level of detail where it can be reproduced.

**Comment by tjablin** [comment] 2019-07-24 16:24
Can you please open a separate issue for discussing the rules around exposing quantization algorithms? I think the rules for exposing quantization algorithms are independent of Guenther's initial question which is:

a) Is the system he describes 16-bit or 4-bit?
b) If it is 4-bit, should we amend the rules to allow 4-bit submissions in closed?

**Comment by guschmue** [comment] 2019-07-24 16:56
I'm with @DilipSequeira and think don't need to be super strict on the precision as long 4 conditions are met:

1. we start with the published weights/model and show what we do to the weights
2. the model is not changed
3. one needs to meet the accuracy target
4. only the calibration dataset is used

The only thing we need to prevent is that people cheat.

**Comment by christ1ne** [comment] 2019-07-24 18:47
Christine will email submitters' list to announce there is a 4-bit related discussion next week.

**Comment by samgd** [comment] 2019-07-24 19:02
Related nuance that came to me after the discussion during the meeting: We may or may not end up disallowing some formats with the approximate aim of tracking the market but what about quantizing to N bits and only using M bits for some M < N (leaving `N - M` set to 0, 1, or undefined)? The hardware can implicitly operate on the M bit? Is this excluded by the current rule set?

**Comment by tjablin** [comment] 2019-07-24 20:46
The whole whitelist is a hack. It's obviously unprincipled and completely unclear how to apply it to various edge cases. The only reason it existed was to get people to register their preferred numerics early so we could choose an appropriate target accuracy. Now that the target accuracy is locked-in, I feel uneasy about int4.

**Comment by DilipSequeira** [comment] 2019-07-25 00:17
I agree the whitelist is a hack. By contrast, I'm uneasy about disallowing implementations that meet all the rules for operator fidelity, post-training calibration, and accuracy, but are excluded from closed because the submitter achieved a higher level of fidelity at low precision than we thought possible.

**Comment by tjablin** [comment] 2019-08-14 16:04
Addressed in [PR46](https://github.com/mlperf/inference_policies/pull/46). PTAL.

**Closed** 2019-08-14 23:38 UTC
Labels: in progress
