### ISSUE TITLE
Finalize quality targets

### ISSUE THREAD

**Issue by petermattson** [mlperf/inference_policies#13] opened 2019-06-27 20:08 UTC
Proposal: 
99% of FP32 accuracy.
We propose these targets stand unless counterproposal on 7/10.

**Comment by Quanticles** [comment] 2019-07-08 18:15
I believe there was a concern about the 1% target accuracy because it can result in a 100+% error in inaccuracy (not sure of the best term for this).

**Example:**  99.5% => 98.5%, no noticeable change in correct answers, but 200% more incorrect answers.
If we agree that 75% => 74%, then perhaps we can say 1% change for accuracy, and 4% change for inaccuracy is okay.

That results in these two constraints (**this is the counterproposal**):
new_accuracy >= 0.99 * old_accuracy
(1 - new_accuracy) >= 1.04 * (1 - old_accuracy)

I don't have a benchmark that we can provide, but I believe there is strong commercial interest for accuracy >99% in the biometrics space.

I realize that we do not currently have a benchmark that would significantly differ by the two-sided constraint, but it would be beneficial in the long run to get the community to start thinking along those lines now.

**Comment by guschmue** [comment] 2019-07-09 01:54
I think ```1% change for accuracy``` is the correct description.

**Comment by jveejay** [comment] 2019-07-09 17:57
@petermattson said via email to inference submitters (moving here for full context):

> Hi folks,
> 
> We need to nail down the inference latency and quality targets. I've opened two Github issues to serve as agenda items.
> 
> We have strawperson proposals for both:
> 
> For latency:
> Imaging benchmarks -- 50ms
> GNMT -- 100ms
> 
> For quality:
> 99% of the FP32 quality level achieved by reference implementations
> 
> I'd suggest we have the 7/10 meeting be the final deadline for counterpropals and require supporting data. If none are put forth, the strawperson becomes the rule. 
> 
> Thoughts, concerns, or alternatives?

**Comment by jveejay** [comment] 2019-07-09 20:17
@guschmue and @itayhubara Can you please update the [table](https://github.com/mlperf/inference/tree/master/v0.5/classification_and_detection) with the quantized model accuracy?

**Comment by jveejay** [comment] 2019-07-09 20:56
I realized that the table didn't have the quantized models, so just put that into the table.

**Comment by jveejay** [comment] 2019-07-09 21:10
The [rules](https://github.com/mlperf/inference_policies/blob/master/inference_rules.adoc#weight-definition-and-quantization) don't clearly state that for quantization we are assuming the same quality target as the fp32 models. We should do a rule fix/clarification as @tjablin recommends.

**Comment by chiragelec** [comment] 2019-07-09 21:24
Vijay, et.al:

 Indeed, would be great to see the updated table so everyone is on the same page.
Also clarification is needed on target for quantized models: is it 99% of fp32 reference model or 99% of quantized reference model (and in that case, the gap btw reference fp32 and reference quantized model also needs to be looked at for meaningful numbers).

In general, we think for quantized models some more leeway may be appropriate to accommodate variants like per-channel vs. per-tensor quantization. Looking forward to hearing views from others in the call.

Thanks,
Chirag

**Comment by tjablin** [comment] 2019-07-09 21:56
99% of the fp32 reference model is the target for all models. There is not a separate quantized and non-quantized division. All implementations have the same accuracy targets.

**Comment by gardner0** [comment] 2019-07-09 23:37
Google has some recent (posted 11 July) data on their own ability to quantize trained FP32 models. Note that even Google is only able to get 98% accuracy on MobileNet V1 (69.568/70.95 = 98% not 99%).

https://medium.com/tensorflow/tensorflow-model-optimization-toolkit-post-training-integer-quantization-b4964a1ea9ba

Most of us attribute God-like powers to Google, so its seems aggressive for MLPerf to assume that other vendors will do better with TensorFlow models. Note that ResNet V2 (no V1 data) seems fine.

**Comment by tjablin** [comment] 2019-07-09 23:40
The MobileNet reference model we're using only goes to 69.86%

**Comment by jveejay** [comment] 2019-07-09 23:47
Tom, that is the fp32 accuracy I assume?!

Typed on a small screen, excuse brevity and typos.
vj.

________________________________

**Comment by tjablin** [comment] 2019-07-09 23:51
It's FP32. The FP32 accuracies for the image models are all here: https://github.com/mlperf/inference/blob/master/v0.5/classification_and_detection/README.md

**Comment by jveejay** [comment] 2019-07-09 23:56
Roger that. Now if we can just nail down the fp32 target quality on the table then that'd be a great step forward.

Typed on a small screen, excuse brevity and typos.
vj.

________________________________

**Comment by christ1ne** [comment] 2019-07-17 18:28
duplicate of #17

**Closed by christ1ne** 2019-07-17 18:28 UTC
