### ISSUE TITLE
Submission auditing rules for LoadGen

### ISSUE THREAD

**Issue by jveejay** [mlperf/inference_policies#22] opened 2019-07-24 15:51 UTC
William from Qualcomm asked: 

"Will MLperf have submission auditing rule on running the loadgen version command to report the signature of source files used in the current build of the app? Since current loadgen is implemented on python and python does not run on android, we integrated loadgen with our framework and we removed these source files as we don’t use them. Will Mlperf be mandating the loadgen version command to function during result submission auditing?"

**Comment by briandersn** [comment] 2019-07-24 17:31
The version_generator.py runs at build time on the host, not at runtime on the device, so it should be able to work even for Android.

I would like to make version_generator.py a requirement since it is a good sanity check that submitters are running with a valid loadgen.

**Comment by christ1ne** [comment] 2019-07-24 19:01
WG: need to clarify in the submission policy doc for the auditing process, including this issue. 
Regarding this issue: for people who needs more support due to other their integration needs on loadgen, they need to upstream their needed changes to bindings directory.

**Comment by christ1ne** [comment] 2019-07-31 18:44
duplicate of #31

**Closed by christ1ne** 2019-07-31 18:44 UTC
