### ISSUE TITLE
Clarify quantization rule description

### ISSUE THREAD

**Issue by jveejay** [mlperf/inference_policies#25] opened 2019-07-24 16:53 UTC
The [quantization rules](https://github.com/mlperf/inference_policies/blob/master/inference_rules.adoc#81-weight-definition-and-quantization) need to be explained more clearly:

> "The quantization method must be publicly described at a level where it could be reproduced. To be considered principled, the description of the quantization method must be much much smaller than the non-zero weights it produce." 

It is not clear to others (and me) what it means that the description of the method must be much much smaller ...

> "Weight quantization algorithm that are similar in size to the non-zero weights they produce."

Hmm... huh?

**Comment by tjablin** [comment] 2019-07-24 20:30
It's a hand wavy reference to Kolmogorov complexity. It disallows quantization methods that are just enormous lookup tables. If a method is documented a 250 page PhD thesis, that's fine. If a method is a couple 100MB of magic numbers, that's not cool. This isn't a rule we can enforce automatically. To paraphrase Justice Potter:

> I shall not today attempt further to define the kinds of material I understand to be embraced within that shorthand description ["unprincipled quantization"], and perhaps I could never succeed in intelligibly doing so. But I know it when I see it...

**Comment by christ1ne** [comment] 2019-07-31 18:43
duplicate of #24

**Closed by christ1ne** 2019-07-31 18:43 UTC
